# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
