# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20180507_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharednotes',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharednotes',
            name='shared_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sharednotes',
            name='shared_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
