# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20180507_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
