# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-05 12:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180605_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt_token',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 12, 42, 49, 56008, tzinfo=utc)),
        ),
    ]
