# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-06 06:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180605_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwt_token',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 6, 6, 39, 13, 862258, tzinfo=utc)),
        ),
    ]
